### ISSUE TITLE
Поддержка нескольких network'ов

### ISSUE THREAD

**Issue by Aracturat** [backmeupplz/coolnetbot#6]
Привет!

Предлагаю добавить поддержку нескольких нетворков.

Тут участвую в нетворке от vas3k, решил закинуть идею использования бота в нашел локальной коммьюнити NskDotNet. Выяснил (в том числе по коду), что сейчас нет поддержки нескольких сообществ для одного пользователя =(. 

Вроде бы это несильно сложно добавить, но стоит вопрос в том, как правильно организовать миграцию текущих данных бота (не работал с Mongo). 

Есть конечно вариант организовать своего бота, который будет копией этого, но не думаю, что это сильно проще, чем добавить поддержку нескольких сообществ в твоего бота.

**Comment by backmeupplz** [comment]
Привет! Хм, подумаю о реализации. Это монго, тут миграция не нужна :) Добавил себе в список задач, спасибо за идею.

**Comment by Aracturat** [comment]
Я могу помочь с PR на эту тему, только не очень понимаю про структуру базы. Будет круто, если как нибудь у тебя найдётся время добавить поддержку нескольких нетворков на уровне хранения, тогда я бы мог запилить остальное :)

**Comment by backmeupplz** [comment]
@Aracturat да там просто вот тут: https://github.com/backmeupplz/coolnetbot/blob/master/src/models/User.ts — нужно password сделать массивом строк, а не строкой :) Использовать ArrayProp, вместо Prop — https://github.com/typegoose/typegoose.

Вместо миграции, перед деплоем могу просто пробежаться по всем записям в БД запросом и сменить `password: string` на `password: string[]`.

Потом нужно просто поменять, как работают команды https://github.com/backmeupplz/coolnetbot/blob/master/src/commands/network.ts и https://github.com/backmeupplz/coolnetbot/blob/master/src/commands/nonetwork.ts. Ну и https://github.com/backmeupplz/coolnetbot/blob/master/src/commands/help.ts актуализировать :)

**Comment by backmeupplz** [comment]
Крач, сделано. Подробности в /help. Теперь можно в нескольких сообществах сразу пить кофе.
